### ISSUE TITLE
Simulatore richiesta azione agente

### ISSUE THREAD

**Issue by matteo-conti-97** [retarded-reward/collaborative-learning#11]
Implementare la richiesta dell'azione all'agente da parte del nodo, questo prevede la raccolta e l'invio dello stato all'agente, l'attesa della ricezione dell'azione richiesta e l'esecuzione dell'azione ricevuta

**Comment by Torkin1** [comment]
- [x] Invio stato (implementato in #14, #15)
- [x] Ricezione azione (implementato in #16)
