### ISSUE TITLE
Bug compute_reward in action do_nothing

### ISSUE THREAD

**Issue by matteo-conti-97** [retarded-reward/collaborative-learning#79]
Method compute_reward, when called in method do_nothing, cause segmentation fault (sometimes even kernel segmentation fault) when executing include_reward_term for the energy penalty

**Comment by Torkin1** [comment]
Il problema sta nel fatto che il valore `SelectPowerSource` per `last_selected_power_source` è impostato a < 0 quando viene selezionata l'azione `do_nothing`. Pertanto, quando `compute_reward` tenta di accedere al `cost_per_mWh` della `PowerSource` nel vettore delle power sources usando come indice il valore di `last_selected_power_source` finisce out of bounds.
